version: "3.9"

services:
  mysql-dev:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: kmikus
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
